---
title: "Subset expression figures"
output: html_document
params:
  marker_yml: "../../markers/lin_cycif-markers.yml"
  input_rds_dir: "../../output/squirrel/lin-cycif_processed/"
  assignments: "../../output/squirrel/astir_assignments/lin_cycif_astir_assignments.csv"
  expression_pdf: "expression.pdf"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(scater)
  library(ComplexHeatmap)
  library(pheatmap)
  library(tidyverse)
  
})

devtools::load_all("/home/ltri/campbell/share/projects/taproom")
```
```{r}
# dir("../../markers")
```


NO LONGER SUBSET

```{r}
markers <- read_markers(params$marker_yml)
```

```{r}
rds_files <- dir(params$input_rds_dir, pattern="rds", full.names = TRUE)

sces <- lapply(rds_files, function(f) {
  s <- readRDS(f)
  for(i in names(rowData(s))) {
    rowData(s)[[ i ]] <- NULL
  }
  s
})

non_null_names <- which(!sapply(sces, is.null))
sces <- sces[non_null_names]

sce <- do.call("cbind", sces)
```

```{r}
subset_assignments <- read_csv(params$assignments)
sce <- sce[, subset_assignments$X1]
```

```{r}
subset_assignments$X1 <- NULL
sce$cell_type <- get_celltypes(subset_assignments)
```

```{r fig.width=25, fig.height = 6}
ct_markers <- unique(unlist(markers$cell_types))
heatmap_markers <- createHeatmap(sce[ct_markers,])
draw(heatmap_markers)
```

```{r}
pdf(params$expression_pdf, width = 20, height = 4)
draw(heatmap_markers)
dev.off()
```


```{r fig.width=25, fig.height = 6}
heatmap <- createHeatmap(sce)
draw(heatmap)
```


```{r}
sce <- runPCA(sce, ncomponents = 10)
sce <- runUMAP(sce)
```

```{r}
plotUMAP(sce, colour_by = "cell_type")
```

```{r}
sce <- calculateQCMetrics(sce, exprs_values = "logcounts")
hist(sce$total_logcounts, breaks = 100)
```



