---
title: "Alternative masks cluster assignment"
author: "Michael Geuenich"
date: "June 7, 2020"
output: html_document
params:
  cells: "output/squirrel/sces/schapiro_alt-Cy1x8_35-Schulz-sce.rds"
  csvs: "output/squirrel/results/alternative_masks/Phenograph_clusters_Cy1x8_35-Schulz_specified_markers_k50.csv"
  markers_list: "markers/schapiro-markers.yml"
  core: "Cy1x8_35"
  user: "Schulz"
  method: ""
  markers: ""
  cluster: ""
  output_dir: ""
  seed: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../../')
library(tidyverse)
library(cowplot)
library(ComplexHeatmap)
library(SingleCellExperiment)
library(yaml)
library(GSVA)
library(pheatmap)
library(taproom)
source('../../scripts/functions.R')
```

```{r}
# Read in markers
markers <- read_markers(params$markers_list)

# Read in RDS file
sce <- readRDS(params$cells)

# Read in clustering results
clustering_df <- read_csv(params$csvs)# %>% column_to_rownames("id")
names(clustering_df)[2] <- "cluster"
clustering_df$cluster <- as.character(clustering_df$cluster)
```


Gene set enrichment analysis
```{r}
expression_mat <- logcounts(sce) %>% 
  t() %>% 
  as_tibble() %>% 
  mutate(id = colnames(sce))

expression_mat <- expression_mat %>% 
  left_join(select(clustering_df, id, cluster)) %>% 
  select(-id)

assignments <- assign_clusters(expression_mat, markers)

GSVA_assignment <- assignments$assignment
manual_assignment <- manual_cluster_assignment(assignments$expression, markers)

cell_assignments <- left_join(clustering_df, select(GSVA_assignment, cluster, GSVA_cell_type)) %>% 
  left_join(manual_assignment)

cell_assignments$core <- paste(params$core, "-", params$user)
```


```{r message=F}
if(is.null(params$seed)){
  file_name <- paste0(params$output_dir, "Alternative_masks-",
                                  params$method, "-cell_type_assignments-",
                                  params$core, "-", params$user, "-", 
                                  params$markers, "-", params$cluster, ".csv")
  cell_assignments$seed <- NA
}else{
  file_name <- paste0(params$output_dir, "Alternative_masks-",
                                  params$method, "-cell_type_assignments-",
                                  params$core, "-", params$user, "-", "seed_", params$seed, "-",
                                  params$markers, "-", params$cluster, ".csv")
  cell_assignments$seed <- params$seed
}

write_csv(cell_assignments, file_name)

```