---
title: "Approaches-comparison"
author: "Michael Geuenich"
date: "June 7, 2020"
output: html_document
params:
  cells: "../output/v4/zurich1_subset/zurich1_subset_sce.rds"
  celltypes: "../output/v4/zurich1_subset/zurich1_subset_assignments_type.csv"
  cohort: "zurich1"
  markers_list:
  output_dir:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/imc-2020/')
library(tidyverse)
library(cowplot)
library(ComplexHeatmap)
library(SingleCellExperiment)
library(yaml)
library(GSVA)
library(pheatmap)
devtools::load_all('~/taproom/')
```

This notebook is used to compare the accuracy of different approaches based on the expression of marker genes.

```{r}
# Read in markers
markers <- read_markers(params$markers_list)

# Read in RDS file
sce <- readRDS(params$cells)

# Get cell types
astir_types <- read_csv(params$celltypes)
cell_names <- astir_types$X1
astir_types$X1 <- NULL
astir_types <- get_celltypes(astir_types)
names(astir_types) <- cell_names

# Add cell types to sce
sce$cluster <- astir_types[colnames(sce)]

# Create list of files to be read in
files <- dir(params$output_dir, 
             pattern=paste0("clusters_", params$cohort, "*.*"), 
             full.names = TRUE)
```


Gene set enrichment analysis
```{r}
gsva <- gsva(logcounts(sce),
          markers$cell_types,
          method="gsva")

df_gsva <- t(gsva) %>% 
  as.data.frame() %>% 
  rownames_to_column("id") %>% 
  gather(pathway, score, -id) %>% 
  as_tibble()
```


```{r message=F}
# Read in and concatenate all output files
methodOutputs <- lapply(files, function(f) {
  cluster_df <- read_csv(f)
  names(cluster_df)[2] <- "cluster"
  cluster_df$cluster <- as.character(cluster_df$cluster)
  cluster_df$method <- paste0(cluster_df$method, "-", cluster_df$params)
  cluster_df$params <- NULL
  cluster_df
}) %>% 
  bind_rows()

# Create analogous df for astir
astir_df <- tibble(
  id = colnames(sce),
  cluster = astir_types[colnames(sce)],
  method = "astir"
)

# combine everything into one dataframe
methods <- bind_rows(methodOutputs, astir_df) %>% 
  inner_join(df_gsva, methods, by = "id")
```


Plotting
```{r message = F, fig.height=12, fig.width = 10}
# Boxplot: gsva scores per cell type
filter(methods, method == "astir") %>% 
  ggplot(aes(x = cluster, y = score)) +
  geom_boxplot() +
  facet_wrap(~ pathway) +
  astir_paper_theme()


# Create summary with mean score per pathway/method/cluster
# Normalize mean scores
# Remove other & unknown cells
methods.summary <- group_by(methods, pathway, method, cluster) %>% 
  summarize(mean_score = mean(score)) %>% 
  ungroup() %>% 
  filter(!grepl("Other|Unknown", cluster)) %>% 
  group_by(pathway, method) %>% 
  mutate(mean_score = (mean_score - mean(mean_score)) / sd(mean_score)) %>% 
  ungroup() %>% 
  group_by(cluster, method) %>% 
  mutate(thresh_score = mean_score == max(mean_score))

# Plot heatmap
methods.summary %>% 
  ggplot(aes(x = cluster, y = pathway, fill = mean_score)) +
  geom_tile() +
  scale_fill_viridis_c() +
  facet_wrap(~ method, scales = "free_x") +
  astir_paper_theme()
```

```{r fig.width=6, fig.height=20}
# Plot boolean heatmap
methods.summary %>% 
  filter(!grepl("Other|Unknown", cluster)) %>% 
  ggplot(aes(x = cluster, y = pathway, fill = thresh_score)) +
  geom_tile() +
  scale_fill_viridis_d() +
  facet_wrap(~ method, scales = "free_x", ncol = 1) +
  astir_paper_theme()

write.csv(methods.summary, 
          file = paste0(params$output_dir, "Assessment-individual-heatmap-",
                                   params$cohort, ".csv"),
          col.names = T, row.names = F, sep = ",")
```


```{r fig.height=6}
df4 <- group_by(methods.summary, pathway, method) %>% 
  summarise(clusters_per_cell_type = sum(thresh_score)) %>% 
  dplyr::mutate(clusters_per_cell_type = as.factor(clusters_per_cell_type))

#Calculate the scores for each method
scores <- df4 %>%
  mutate(score = case_when(
    clusters_per_cell_type == 1 ~ 1,
    clusters_per_cell_type != 1 ~ -1
  )) %>%
  group_by(method) %>%
  dplyr::summarise(score = sum(score))

clPerType <- pivot_wider(df4, names_from = pathway, 
                         values_from = clusters_per_cell_type) %>% 
  left_join(scores, by = "method") %>%
  mutate(method = str_replace(method, "_", " ")) %>% 
  mutate(method = str_replace(method, "_", "-")) %>% 
  mutate(method = str_replace(method, "astir", "Astir")) %>% 
  column_to_rownames(var = "method")

# Write out the data to be plotted for further use by subsequent scripts
write.csv(clPerType, file = paste0(params$output_dir, "Assessment-heatmap-",
                                   params$cohort, ".csv"),
          col.names = T, row.names = T, sep = ",")

# Create matrix
clPerType.mat <- clPerType %>% 
  select(-score) %>% 
  as.matrix()

# Colour palette
gradient<- colorRampPalette(c("#FFEBEE", "#F50025"))
pal <- c("#FFB60A", "#648FFF", 
         gradient(max(as.integer(levels(df4$clusters_per_cell_type))) - 1))
names(pal) <- c(0:max(as.integer(levels(df4$clusters_per_cell_type))))

# Heatmap annotation
plottingOrder = clPerType %>% 
  arrange(desc(score)) %>% 
  rownames()

ha = rowAnnotation(Score = anno_barplot(clPerType$score, gp = gpar(fill = "lightgrey")),
                   width = unit(2, "cm"))

Heatmap(clPerType.mat, col = pal,
        right_annotation = ha,
        row_names_side = "left",
        row_order = plottingOrder,
        width = unit(5.5, "cm"),
        height = unit(8, "cm"),
        name = "# of clusters")
```
