---
title: "ClusterX"
author: "Michael Geuenich"
date: "May 29, 2020"
output: html_document
params:
  markers: "specified_markers"
  create_csv: FALSE
  cells: "../../output/v4/zurich1_subset/zurich1_subset_sce.rds"
  celltypes: "../../output/v4/zurich1_subset/zurich1_subset_assignments_type.csv"
  cellstates: "../../output/v4/zurich1_subset/zurich1_subset_assignments_state.csv" 
  cohort: "zurich1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SingleCellExperiment)
library(tidyverse)
library(devtools)
library(factoextra)
library(ComplexHeatmap)
library(scater)
library(dichromat)
library(randomcoloR)
library(viridis)
devtools::load_all('../../../taproom/')
source("scripts/functions.R")

library(cytofkit)
library(ggalluvial)
```


First read in all sc data and assign cell type
```{r message=F, warning=F}
# read in data
sce <- assignIdentity2(params$cells, params$celltypes, params$cellstates)
pathways <- sce$pathways
sce <- sce$sce

# Just for the time being until we switch everything over to remove s' at the end
sce$cell_type[which(sce$cell_type == "B cell")] <- "B cells"
sce$cell_type[which(sce$cell_type == "T cell")] <- "T cells"
```

```{r}
if(params$markers == "all_markers"){
  imc.data <- t(logcounts(sce))
  
  # I will use this variable in the future to evaluate whether sections of code
  # should be executed
  evalStatement <- F
}else if(params$markers == "specified_markers"){
  if(params$cohort == "basel" | params$cohort == "zurich1"){
    markers <- read_markers("../../markers/jackson-2020-markers-v2.yml")
  }else if(params$cohort == "wagner"){
    markers <- read_markers("../../markers/wagner-2019-markers.yml")
  }
  
  imc.data <- t(logcounts(sce[unique(unlist(markers$cell_types)),]))
  evalStatement <- T
}
```

```{r}
# ClusterX requires a tsne plot to start with
imc.tsne <- cytof_dimReduction(data=imc.data, method = "tsne")
imc.clusterX.cluster <- cytof_cluster(ydata = imc.tsne, method = "ClusterX")

sce$clusterX <- imc.clusterX.cluster
```


```{r}
ClusterX <- sce %>% colData() %>% as.data.frame() %>% select(id, "clusterX")
rownames(ClusterX) <- c()
ClusterX$method <- "ClusterX"
ClusterX$params <- paste(params$markers, "Default", sep = "_")
write.csv(ClusterX, file = paste0("../../output/v4/results/ClusterX_clusters_", params$cohort,
                                  "_", params$markers, "_default.csv"),
          col.names = T, row.names = F, sep = ",")
```

```{r}
ClusterX.alluv <- sce %>% colData() %>% as.data.frame() %>% 
    select(cell_type, clusterX) %>% group_by(cell_type, clusterX) %>% 
  count()

create.alluvial(ClusterX.alluv, "Cell type - ClusterX")
```

```{r}
ClusterX.alluv <- sce %>% colData() %>% as.data.frame() %>% 
    select(type_state, clusterX) %>% group_by(type_state, clusterX) %>% 
  count()

create.alluvial(ClusterX.alluv, "Cell state - ClusterX")
```

```{r eval = evalStatement, include = evalStatement, fig.width=10}
lc <- scale(imc.data)
thresh <- 2
lc[lc > thresh] <- thresh
lc[lc < -thresh] <- -thresh


clusterX.ha <- 
  HeatmapAnnotation(`Cell type` = sce$cell_type,
                    `clusterX cluster` = as.factor(sce$clusterX),
                    which="column",
                    col = list(`Cell type` = jackson_basel_colours()),
                    `clusterX cluster` = distinctColorPalette(length(unique(sce$clusterX))))

clusterX.type_exprs <- Heatmap(t(lc), 
                                name = "Expression",
                                column_title = "Cell",
                                col=viridis(100),
                                top_annotation = clusterX.ha,
                                show_column_names = FALSE,
                                column_order = order(sce$clusterX))

draw(clusterX.type_exprs)
```

```{r eval = evalStatement, include = evalStatement, fig.width=20, fig.height=10}
# start creating theme
astir_paper_theme <- 
  cowplot::theme_cowplot(font_size = 12)
  
  
phenograph.violin <- sce %>% 
  colData() %>% 
  as.data.frame %>% 
  select(pathways, 
         clusterX) %>% 
  pivot_longer(cols = pathways, 
               names_to = "pathway", values_to = "activation")

phenograph.violin$clusterX <- as.factor(phenograph.violin$clusterX)


ggplot(phenograph.violin, aes(x = clusterX, y = activation)) +
  geom_violin(width = 0.08) +
  facet_wrap(c("pathway")) +
  astir_paper_theme

ggplot(phenograph.violin, aes(x = clusterX, y = activation)) +
  geom_boxplot() +
  facet_wrap(c("pathway")) +
  astir_paper_theme

```


Create plots to evaluate the accuracy of astir.
```{r eval = evalStatement, include=evalStatement}
imc.data <- as.data.frame(imc.data)
  
imc.data$cell_type <- sce$cell_type
imc.data$clusterX <- sce$clusterX

if(params$cohort == "wagner"){
  selMarkers <- c("CD45", "FAP")
}else if(params$cohort == "basel" | params$cohort == "zurich1"){
  selMarkers <- c("Vimentin", "Cytokeratin 19")
}

astir.mean <- imc.data %>% 
                    group_by(cell_type) %>% 
                    summarise_at(vars(selMarkers[1]:selMarkers[2]), mean) %>% 
                    dplyr::rename(cluster = cell_type) %>% 
                    mutate(algorithm = "astir")

clusterX.mean <- imc.data %>% 
                    group_by(clusterX) %>% 
                    summarise_at(vars(selMarkers[1]:selMarkers[2]), mean) %>% 
                    dplyr::rename(cluster = clusterX) %>% 
                    mutate(algorithm = "clusterX") %>% 
                    mutate(cluster = as.character(cluster))


comparison.summary <- bind_rows(astir.mean, clusterX.mean)


# ggplot(comparison.summary, aes(x = `E-Cadherin`, y = CD45)) +
#   geom_point() +
#   facet_wrap("algorithm") + 
#   xlim(0, max(imc.data$`E-Cadherin`)) +
#   ylim(0, max(imc.data$CD45)) +
#   ggtitle("Mutually exclusive markers")
# 
# ggplot(comparison.summary, aes(x = CD3, y = CD45)) +
#   geom_point() +
#   facet_wrap("algorithm") + 
#   xlim(0, max(imc.data$CD3)) +
#   ylim(0, max(imc.data$CD45)) +
#   ggtitle("Co-occuring markers")

```

Save the comparison file for future analyses.
```{r eval = evalStatement, include=evalStatement}
write.csv(comparison.summary, paste0("../../output/v4/results/ClusterX_astirComparison_", 
                                    params$cohort, ".csv"),
          row.names = F)
```