---
title: "Final approaches comparison"
author: "Michael Geuenich"
date: "June 27, 2020"
output: html_document
params:
  Jackson: "../output/v4/results/Assessment-heatmap-Jackson.csv"
  Catena: ""
  Schulz: "../output/v4/results/Assessment-heatmap-Schulz.csv"
  Jackson_indiv: ""
  Catena_indiv: ""
  Schulz_indiv: ""
  output_dir: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/imc-2020/')
library(cowplot)
library(ggpubr)
library(ComplexHeatmap)
library(tidyverse)
devtools::load_all('~/taproom/')
```

Read in data
```{r}
Jackson <- read_csv(params$Jackson) %>% 
  mutate_if(colnames(.) != "score", as.factor) %>% 
  column_to_rownames("X1")

Catena <- read_csv(params$Catena) %>% 
  mutate_if(colnames(.) != "score", as.factor) %>% 
  column_to_rownames("X1")

Schulz <- read_csv(params$Schulz) %>% 
  mutate_if(colnames(.) != "score", as.factor) %>% 
  column_to_rownames("X1")
```

```{r fig.width=12, fig.height = 5.5}
# Find largest level
Jackson.max <- lapply(Jackson[Jackson %>% 
              select(-score) %>% 
              colnames], FUN = levels) %>% 
  unlist() %>% 
  as.numeric() %>% 
  max()

Catena.max <- lapply(Catena[Catena %>% 
              select(-score) %>% 
              colnames], FUN = levels) %>% 
  unlist() %>% 
  as.numeric() %>% 
  max()

Schulz.max <- lapply(Schulz[Schulz %>% 
              select(-score) %>% 
              colnames], FUN = levels) %>% 
  unlist() %>% 
  as.numeric() %>% 
  max()

max.clusters <- max(Jackson.max, Catena.max, Schulz.max)
if(max.clusters > 10){
  max.clusters <- 10
}


# Create colour palette
gradient<- colorRampPalette(c("#FFEBEE", "#F50025"))
pal <- c("#FFDA1F", "#00D262", 
         gradient(max.clusters - 1))
names(pal) <- c(0:(max.clusters - 1), "10+")

tooHigh <- as.character(c(0:9))

# Create matrices to plot
Jackson.mat <- Jackson %>%
  select(-score) %>% 
  as.matrix()

Jackson.mat[!(Jackson.mat %in% tooHigh) & !is.na(Jackson.mat)] <- "10+"

Catena.mat <- Catena %>%
  select(-score) %>%
  as.matrix()

Catena.mat[!(Catena.mat %in% tooHigh)] <- "10+"

Schulz.mat <- Schulz %>% 
  select(-score) %>% 
  as.matrix()

Schulz.mat[!(Schulz.mat %in% tooHigh)] <- "10+"


# Create heatmap annotations
# define plotting order
scores <- data.frame(Jackson$score, Catena$score, Schulz$score) 
scores$mean <- rowMeans(scores[, 1:3])
rownames(scores) <- rownames(Jackson)

plottingOrder = scores %>% 
  arrange(desc(mean)) %>% 
  rownames()
  
# Annotations
Jackson.ha = rowAnnotation(Score = anno_barplot(Jackson$score, 
                                              gp = gpar(fill = "lightgrey")),
                   width = unit(2, "cm"))
Catena.ha = rowAnnotation(Score = anno_barplot(Catena$score,
                                              gp = gpar(fill = "lightgrey")),
                    width = unit(2, "cm"))
Schulz.ha = rowAnnotation(Score = anno_barplot(Schulz$score, 
                                              gp = gpar(fill = "lightgrey")),
                   width = unit(2, "cm"))


Jackson.hm <- Heatmap(Jackson.mat, col = pal,
                    row_order = plottingOrder,
                    right_annotation = Jackson.ha,
                    column_title = "Jackson",
                    row_names_side = "left",
                    row_names_max_width = unit(7, "cm"),
                    name = "# of clusters")
Catena.hm <- Heatmap(Catena.mat, col = pal,
                      row_order = plottingOrder,
                      right_annotation = Catena.ha,
                      column_title = "Catena",
                      row_names_side = "left",
                      row_names_max_width = unit(7, "cm"),
                      name = "# of clusters")
Schulz.hm <- Heatmap(Schulz.mat, col = pal,
                     row_order = plottingOrder,
                     right_annotation = Schulz.ha,
                     show_heatmap_legend = F,
                     column_title = "Schulz",
                     show_row_names = F)


Jackson.hm + Catena.hm + Schulz.hm
```

```{r}
pdf(file = paste0(params$output_dir, "Final_benchmarking_heatmap.pdf"), width = 14, height = 6)
  Jackson.hm + Catena.hm + Schulz.hm
dev.off()
```



Create individual heatmaps
```{r fig.width=45, fig.height=13}
Jackson <- read_csv(params$Jackson_indiv)
Jackson <- Jackson %>% 
  mutate(method = str_replace(method, "_", "\n")) %>% 
  mutate(method = str_replace(method, "_", "-")) %>% 
  mutate(method = str_replace(method, "astir", "Astir"))

Catena <- read_csv(params$Catena_indiv)
Catena <- Catena %>% 
  mutate(method = str_replace(method, "_", "\n")) %>% 
  mutate(method = str_replace(method, "_", "-")) %>% 
  mutate(method = str_replace(method, "astir", "Astir"))

Schulz <- read_csv(params$Schulz_indiv)
Schulz <- Schulz %>% 
  mutate(method = str_replace(method, "_", "\n")) %>% 
  mutate(method = str_replace(method, "_", "-")) %>% 
  mutate(method = str_replace(method, "astir", "Astir"))


summary.heatmap.theme <- function(){
  astir_paper_theme() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())
  #scale_color_discrete("Corresponds to cellytpe")
  #scale_colour_discrete("Continents")
}

Jackson.hm <- Jackson %>% 
  filter(!grepl("Other|Unknown", cluster)) %>% 
  ggplot(aes(x = cluster, y = pathway, fill = thresh_score)) +
  geom_tile() +
  scale_fill_viridis_d() +
  facet_wrap(~ method, scales = "free_x", nrow = 1) +
  summary.heatmap.theme()

Catena.hm <- Jackson %>% 
  filter(!grepl("Other|Unknown", cluster)) %>% 
  ggplot(aes(x = cluster, y = pathway, fill = thresh_score)) +
  geom_tile() +
  scale_fill_viridis_d() +
  facet_wrap(~ method, scales = "free_x", nrow = 1) +
  summary.heatmap.theme()

Schulz.hm <- Schulz %>% 
  filter(!grepl("Other|Unknown", cluster)) %>% 
  ggplot(aes(x = cluster, y = pathway, fill = thresh_score)) +
  geom_tile() +
  scale_fill_viridis_d() +
  facet_wrap(~ method, scales = "free_x", nrow = 1) +
  summary.heatmap.theme()


ggarrange(Jackson.hm, Catena.hm, Schulz.hm, nrow = 5)
```
