---
title: "Unknown and other differential expression"
author: "Michael Geuenich"
date: "August 31, 2020"
output: html_document
params:
  cells: "output/v6/wagner_subset/wagner_subset_sce.rds"
  types: "output/v6/wagner_subset/wagner_subset_assignments_type.csv"
  state: "output/v6/wagner_subset/wagner_subset_assignments_state.csv"
  thresh: 0.5
  cohort: "wagner"
  output_dir: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../../')
library(SingleCellExperiment)
library(scater)
library(tidyverse)
library(devtools)
library(broom)
source("../../scripts/functions.R")
devtools::load_all("../../../taproom/")
```

```{r fig.height=6, fig.width=7}
sce <- readRDS(params$cells)
type <- read_csv(params$types)

type$cell_type <- get_celltypes(select(type, -X1), params$thresh) 
type <- select(type, X1, cell_type) %>%
  column_to_rownames("X1")
colData(sce)["cell_type"] <- type[colnames(sce),]

# Just for the time being until we switch everything over to remove s' at the end
sce$cell_type[which(sce$cell_type == "B cell")] <- "B cells"
sce$cell_type[which(sce$cell_type == "T cell")] <- "T cells"

#sce <- assignIdentity(params$cells, params$types, params$state, thresh = params$thresh)$sce

get_lm_simple <- function(expr, cell_type_1, cell_type_2){
  df <- expr %>% 
    filter(cell_type == cell_type_1[1] | cell_type == cell_type_1[2] | cell_type == cell_type_2)  %>% 
    mutate(cell_type = ifelse(cell_type == cell_type_1[1] | cell_type == cell_type_1[2], 
                              "Unknown_Other", "Assigned")) %>% 
    rem_low_cell_cores() %>% 
    group_by(core, Protein) %>% 
    mutate(cell_type = factor(cell_type, levels  = c("Assigned", "Unknown_Other"))) %>% 
    do(tidy(lm(Expression ~ cell_type, data = .))) %>% 
    filter(term != "(Intercept)")
  
  design <- expr %>% 
    filter(cell_type == cell_type_1[1] | cell_type == cell_type_1[2] | cell_type == cell_type_2)  %>% 
    mutate(cell_type = ifelse(cell_type == cell_type_1[1] | cell_type == cell_type_1[2], 
                              "Unknown_Other", "Assigned")) %>%  
    rem_low_cell_cores() %>% 
    group_by(core, Protein) %>% 
    mutate(cell_type = factor(cell_type, levels  = c("Assigned", "Unknown_Other"))) %>% 
    model.matrix(~cell_type, .)
  
  list(df, design)
}

plot_lm <- function(df, title = ""){
  df %>% 
    ggplot(aes(x = Protein, y = estimate)) +
    geom_boxplot() +
    ggtitle(title) +
    astir_paper_theme() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    geom_hline(yintercept = 0, color = "red")
}

plot_estimate_hist <- function(df, title){
  df %>% 
    ggplot(aes(x = estimate)) +
    geom_histogram(bins = 100) +
    astir_paper_theme() +
    ggtitle(title)
}

allDuplicated <- function(vec){
  front <- duplicated(vec)
  back <- duplicated(vec, fromLast = TRUE)
  all_dup <- front + back > 0
  return(all_dup)
}

rem_low_cell_cores <- function(df){
  number_of_proteins <- length(unique(df$Protein))
  
  cores_keep <- df %>% 
    group_by(core, cell_type) %>% 
    tally() %>% 
    filter(n > number_of_proteins) %>% 
    pull(core)
  
  cores_keep <- cores_keep[allDuplicated(cores_keep)]
  
  df %>% 
    filter(core %in% cores_keep)
}
```

```{r}
if(params$cohort == "wagner"){
  expression <- logcounts(sce) %>% 
    t() %>% as.data.frame() %>% 
    mutate(cell_type = sce$cell_type) %>% 
    mutate(core = sce$patient_id) %>%
    pivot_longer(cols = -c(cell_type, core), values_to = "Expression", names_to = "Protein") %>% 
    mutate(Expression = as.numeric(Expression))
}else if(params$cohort == "schapiro"){
  sce$id <- colnames(sce)
  
  expression <- logcounts(sce) %>% 
    t() %>% as.data.frame() %>% 
    mutate(cell_type = sce$cell_type) %>% 
    mutate(core = sub("_[^_]+$", "", sce$id)) %>%
    pivot_longer(cols = -c(cell_type, core), values_to = "Expression", names_to = "Protein") %>% 
    mutate(Expression = as.numeric(Expression))
}else if(params$cohort == "lin_cycif"){
  expression <- logcounts(sce) %>% 
    t() %>% as.data.frame() %>% 
    mutate(cell_type = sce$cell_type) %>% 
    mutate(core = rownames(colData(sce))) %>%
    mutate(core = sub("_[^_]+$", "", .$core)) %>%
    #mutate(core = sub("_[^_]+$", "", sce$core)) %>%
    pivot_longer(cols = -c(cell_type, core), values_to = "Expression", names_to = "Protein") %>% 
    mutate(Expression = as.numeric(Expression))
}else{
  expression <- logcounts(sce) %>% 
    t() %>% as.data.frame() %>% 
    mutate(cell_type = sce$cell_type) %>% 
    mutate(core = sce$core) %>%
    pivot_longer(cols = -c(cell_type, core), values_to = "Expression", names_to = "Protein") %>% 
    mutate(Expression = as.numeric(Expression))
}

expression <- expression %>% 
  mutate(Protein = ifelse(Protein == "Progesterone Receptor A/B antibody 1", "PR A/B ab 1", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "Progesterone Receptor A/B antibody 2", "PR A/B ab 2", Protein)) %>%
  mutate(Protein = ifelse(Protein == "PRAB", "PR A/B", Protein)) %>%
  mutate(Protein = ifelse(Protein == "Histone H3 antibody 1", "Histone H3 ab 1", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "Histone H3 antibody 2", "Histone H3 ab 2", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "HistoneH3", "Histone H3", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "Carbonic Anhydrase IX", "CAIX", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "CarbonicAnhydraseIX", "CAIX", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "cMYC", "c-MYC", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "ECadherin", "E Cadherin", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "E-cadherin", "E Cadherin", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "K14", "Cytokeratin 14", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "K5", "Cytokeratin 5", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "K7", "Cytokeratin 7", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "Cytokeratin7", "Cytokeratin 7", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "K8K18", "Cytokeratin 8/18", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "Cytokeratin8-18", "Cytokeratin 8/18", Protein)) %>% 
  mutate(Protein = ifelse(Protein == "S6", "phospho S6", Protein))
```


```{r}
unknown_data <- expression %>% 
  mutate(cell_type = ifelse(cell_type == "Unknown" | cell_type == "Other", 
                            "Unknown_Other", "Assigned")) %>% 
  rem_low_cell_cores() %>% 
  mutate(cell_type = factor(cell_type, levels  = c("Assigned", "Unknown_Other"))) %>% 
  group_by(core, Protein) 

unknown <- unknown_data %>% 
  do(tidy(lm(Expression ~ cell_type, data = .))) %>% 
  filter(term != "(Intercept)")

plot_lm(unknown, "Unknown & Other vs Assigned")
head(model.matrix(~cell_type, unknown_data))


# other_data <- expression %>% 
#   filter(cell_type != "Unknown") %>% 
#   mutate(cell_type = ifelse(cell_type == "Other", "Other", "Assigned")) %>% 
#   rem_low_cell_cores() %>% 
#   mutate(cell_type = factor(cell_type, levels  = c("Other", "Assigned"))) %>%  
#   group_by(core, Protein)
# 
# other <-  other_data %>% 
#   do(tidy(lm(Expression ~ cell_type, data = .))) %>% 
#   filter(term != "(Intercept)")
# 
# plot_lm(other)
# head(model.matrix(~cell_type, other_data))
```

```{r}
plot_estimate_hist(unknown, "Unknown & Other")

plot(sort(unknown$estimate))
abline(0,0,col='red')
```


### Now unknown and stromal
```{r fig.height=6, fig.width=7}
unknown_vs_stromal <- get_lm_simple(expression, c("Unknown", "Other"), "Stromal")

plot_lm(unknown_vs_stromal[[1]], "Unknown & Other vs stromal")
head(unknown_vs_stromal[[2]])
```

```{r}
plot_estimate_hist(unknown_vs_stromal[[1]], "Unknown & Other")
```


Final boxplot
```{r fig.height=6, fig.width=7}
unknown_plot <- unknown %>% 
  ungroup() %>% 
  select(Protein, estimate) %>% 
  mutate(origin = "Unknown & Other vs Assigned")

unknown_vs_stromal_plot <- unknown_vs_stromal[[1]] %>% 
  ungroup() %>% 
  select(Protein, estimate) %>% 
  mutate(origin = "Unknown & Other vs Stromal")


box <- rbind(unknown_plot, unknown_vs_stromal_plot)

plot <- box %>% 
  mutate(origin = ifelse(origin == "Unknown & Other vs Assigned", "Unknown & Other vs\nall Assigned", origin)) %>% 
  mutate(origin = ifelse(origin == "Unknown & Other vs Stromal", "Unknown & Other vs\nStromal", origin)) %>% 
  ggplot(aes(x = Protein, y = estimate, fill = origin, color = origin)) +
    geom_hline(yintercept = 0, color = "black") +
    geom_hline(yintercept = 0.5, color = "lightgrey") +
    geom_hline(yintercept = -0.5, color = "lightgrey") +
    geom_hline(yintercept = -1, color = "lightgrey") +
    geom_hline(yintercept = -1.5, color = "lightgrey") +
    geom_hline(yintercept = -2, color = "lightgrey")


if(params$cohort == "basel"){
  plot <- plot +
    geom_hline(yintercept = 3, color = "lightgrey") +
    geom_hline(yintercept = 2.5, color = "lightgrey") +
    geom_hline(yintercept = 2, color = "lightgrey") +
    geom_hline(yintercept = 1.5, color = "lightgrey") +
    geom_hline(yintercept = 1, color = "lightgrey") +
    geom_hline(yintercept = -2, color = "lightgrey")

}else if(params$cohort == "schapiro"){
  plot <- plot +
    geom_hline(yintercept = 3, color = "lightgrey") +
    geom_hline(yintercept = 2.5, color = "lightgrey") +
    geom_hline(yintercept = 2, color = "lightgrey") +
    geom_hline(yintercept = 1.5, color = "lightgrey") +
    geom_hline(yintercept = 1, color = "lightgrey") +
    geom_hline(yintercept = -2, color = "lightgrey")

}else if(params$cohort == "zurich1"){
  plot <- plot +
    geom_hline(yintercept = 3, color = "lightgrey") +
    geom_hline(yintercept = 2.5, color = "lightgrey") +
    geom_hline(yintercept = 2, color = "lightgrey") +
    geom_hline(yintercept = 1.5, color = "lightgrey") +
    geom_hline(yintercept = 1, color = "lightgrey") +
    geom_hline(yintercept = -2, color = "lightgrey")

}else if(params$cohort == "wagner"){
  plot <- plot +
    geom_hline(yintercept = 4.5, color = "lightgrey") +
    geom_hline(yintercept = 4, color = "lightgrey") +
    geom_hline(yintercept = 3.5, color = "lightgrey") +
    geom_hline(yintercept = 3, color = "lightgrey") +
    geom_hline(yintercept = 2.5, color = "lightgrey") +
    geom_hline(yintercept = 2, color = "lightgrey") +
    geom_hline(yintercept = 1.5, color = "lightgrey") +
    geom_hline(yintercept = 1, color = "lightgrey") +
    geom_hline(yintercept = -2, color = "lightgrey") +
    geom_hline(yintercept = -2.5, color = "lightgrey") +
    geom_hline(yintercept = -3, color = "lightgrey") +
    geom_hline(yintercept = -3.5, color = "lightgrey") +
    geom_hline(yintercept = -4, color = "lightgrey") +
    geom_hline(yintercept = -4.5, color = "lightgrey")
} else if(params$cohort == "lin_cycif"){
  plot <- plot +
    geom_hline(yintercept = 3, color = "lightgrey") +
    geom_hline(yintercept = 2.5, color = "lightgrey") +
    geom_hline(yintercept = 2, color = "lightgrey") +
    geom_hline(yintercept = 1.5, color = "lightgrey") +
    geom_hline(yintercept = 1, color = "lightgrey") +
    geom_hline(yintercept = -2, color = "lightgrey") +
    geom_hline(yintercept = -2.5, color = "lightgrey") +
    geom_hline(yintercept = -3, color = "lightgrey") +
    geom_hline(yintercept = -3.5, color = "lightgrey")
}

plot <- plot + geom_boxplot(outlier.colour = "lightgrey", outlier.size = 0.4) +
    guides(color = FALSE) +
    scale_color_manual(values = c("#E4790A", "#8B5B42")) +
    scale_fill_manual(values = c("#E4790A", "#8B5B42")) +
    astir_paper_theme() + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    labs(fill = "Comparison", y = "Coefficient", x = "Feature") + 
    theme(legend.position = "top",
          axis.title = element_text(size=16),
          axis.text = element_text(size=14),
          legend.text = element_text(size=16),
          legend.title = element_text(size=16))

plot
```

```{r}
pdf(file = paste0(params$output_dir, "Unknown-other-differential-expression-", params$cohort, "-", params$thresh, ".pdf"), width = 8, height = 4.5)
  plot
dev.off()
```