---
title: "spatial-figures.Rmd"
output: html_document
params:
  basel_output: ../../output/squirrel/spatial/rds_output_basel.rds
  zurich1_output: ../../output/squirrel/spatial/rds_output_zurich1.rds
  basel_expression: ../../output/squirrel/spatial/summarized-expression-basel.tsv
  zurich1_expression: ../../output/squirrel/spatial/summarized-expression-zurich1.tsv
  basel_metadata: ../../data-raw/jackson-2020/SingleCell_and_Metadata/BaselTMA/Basel_PatientMetadata.csv
  zurich1_metadata: ../../data-raw/jackson-2020/SingleCell_and_Metadata/ZurichTMA/Zuri_PatientMetadata.csv
  cells_counted_basel: ../../output/squirrel/spatial/cells-counted-basel.tsv
  kaplan_meier: km.pdf
  pathway_fig: pw.pdf
  spatial_heatmap: hm.pdf
  pathologist_plot: path.pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages({
  library(tidyverse)
  library(ComplexHeatmap)
  library(viridis)
  library(broom)
  library(survival)
  library(glue)
  library(circlize)
  library(survminer)
})

devtools::load_all("/home/ltri/campbell/share/projects/taproom")
```

# Read in data

```{r read-spatial-output}
basel_output <- readRDS(params$basel_output)
zurich1_output <- readRDS(params$zurich1_output)
```

```{r}
basel_expression <- read_tsv(params$basel_expression)
zurich1_expression <- read_tsv(params$zurich1_expression)
```

Zurich metadata:

```{r}
zm <- read_csv(params$zurich1_metadata)
bm <- read_csv(params$basel_metadata)
```

```{r}
zm_cores_to_use <- filter(zm, location == "CENTER") %>% .$core
bm_cores_to_use <- filter(bm, diseasestatus == "tumor") %>% .$core
```


# Overall heatmap

```{r}
col_fun = colorRamp2(c(-2, 0, 2), c(scales::muted('blue'), "white", scales::muted("red")))
```

```{r}
col_fun2 = colorRamp2(c(-2, 0, 2), c(scales::muted('purple'), "white", scales::muted("green")))
```

```{r}
spatial_score <- c(basel_output$spatial_score, zurich1_output$spatial_score)
cell_num_vec <- c(basel_output$cell_num_vec, zurich1_output$cell_num_vec)
mat <- rbind(basel_output$mat, zurich1_output$mat)
dataset <- c(rep("Basel", length(basel_output$spatial_score)), rep("Zurich", length(zurich1_output$spatial_score)))
```

```{r}
top_annot <- HeatmapAnnotation(`# cells` = anno_barplot(cell_num_vec),
                                     `Spatial score` = spatial_score,
                                     col = list(
                                       `Spatial score` = col_fun2
                                     ),
                               annotation_legend_param = list(
                                 legend_direction = "horizontal"
                               ))

ht <- Heatmap(t(mat), 
                    na_col = "grey90", 
                    show_column_names = FALSE, 
                    col = col_fun,
                    top_annotation = top_annot,
                    column_order = order(spatial_score),
                    name = "Average distance",
                    column_split = dataset,
                    heatmap_legend_param = list(legend_direction = "horizontal"))
draw(ht, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
```




```{r}
pdf(params$spatial_heatmap, width = 11, height = 7)
draw(ht, heatmap_legend_side = "bottom", annotation_legend_side = "bottom",
     padding = unit(c(2, 2, 2, 15), "mm"))
dev.off()
```

# Differential expression

```{r}
df_basel <- enframe(basel_output$spatial_score, "core", "spatial_score") %>% 
  inner_join(basel_expression, by = "core") %>% 
  filter(core %in% bm_cores_to_use)
```

```{r}
df_test_basel <- group_by(df_basel, cell_type, marker) %>% 
  do(tidy(lm(mean_expression ~ spatial_score, data=.))) %>% 
  filter(term == "spatial_score") %>% 
  mutate(q_val = p.adjust(p.value, method="BH"))
```

```{r}
filter(df_test_basel, q_val < 0.05) %>% 
  ggplot(aes(x = cell_type, y = marker, size = -log10(q_val), colour=estimate)) +
  geom_point() +
  scale_colour_gradient2()
```
```{r}
df_zurich <- enframe(zurich1_output$spatial_score, "core", "spatial_score") %>% 
  inner_join(zurich1_expression, by = "core") %>% 
  filter(core %in% zm_cores_to_use)
```

```{r}
df_test_zurich <- group_by(df_zurich, cell_type, marker) %>% 
  do(tidy(lm(mean_expression ~ spatial_score, data=.))) %>% 
  filter(term == "spatial_score") %>% 
  mutate(q_val = p.adjust(p.value, method="BH"))
```

```{r}
filter(df_test_zurich, q_val < 0.05) %>% 
  ggplot(aes(x = cell_type, y = marker, size = -log10(q_val), colour=estimate)) +
  geom_point() +
  scale_colour_gradient2()
```

```{r}
df_test <- inner_join(df_test_basel, df_test_zurich,
           by = c("cell_type", "marker", "term"),
           suffix = c("_basel", "_zurich")) 

```

```{r}
df_cor <- group_by(df_test, cell_type) %>% 
  do(tidy(cor.test(.$estimate_basel, .$estimate_zurich, method="pearson")))
```

```{r}
df_test <- inner_join(df_cor, df_test, by = "cell_type")

roundn <- function(x, n = 2) format(round(x, n), nsmall = n)
```

```{r}
df_test <- mutate(df_test, label = paste0(cell_type, "\n", "Correlation", " = ", roundn(estimate), "\np = ", format(p.value,digits=3)))

# df_test$label2 = expression(paste("rho"))
```


```{r}

df_test %>% 
  filter(!grepl("Unknown|Other", cell_type)) %>% 
  ggplot(aes(x = estimate_basel, y = estimate_zurich)) +
  geom_point(alpha = 0.5, size =2) +
  facet_wrap(~ label, scales = "free",nrow=2) +
  cowplot::theme_cowplot() +
  geom_smooth(method="lm", colour = "darkred", linetype=2) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 3)) +
  theme(strip.text = element_text(face="bold"),
        strip.background = element_rect(fill='white')) +
  labs(x = "Effect size (Basel cohort)", y = "Effect size (Zurich cohort)")
```
```{r}
pdf(params$pathway_fig, width = 9, height = 5)
print(last_plot())
dev.off()
```



# Associating pathway activation

```{r, eval=FALSE}
df_test2 <- bind_rows(
  basel_output$df_test,
  zurich1_output$df_test
)
```

```{r, eval=FALSE}
df_test2$state <- gsub("HALLMARK_", "", df_test$state)
df_test2$dataset <- str_to_title(gsub("1", "", df_test$dataset))

ggplot(df_test2, aes(x = -log10(p.value), y = fct_reorder(state, -log10(p.value)))) +
  geom_point(aes(fill = estimate), shape = 21, size = 4) +
  facet_wrap(~ dataset, scales = "free_x") +
  scale_fill_gradient2(name = "Change with increasing spatial score",
                       breaks = c(-0.01, 0),
                       low = scales::muted("blue"),
                       high = scales::muted("red")) +
  astir_paper_theme() +
  labs(y = "Pathway") +
  theme(legend.position = "bottom")

```


```{r, eval=FALSE}
pdf(params$pathway_fig, width = 9, height = 3)
print(last_plot())
dev.off()
```


# Survival analysis for Basel

```{r}
mdata <- read_csv(params$basel_metadata)

df_surv <- filter(mdata, diseasestatus == "tumor") %>% 
  select(PID, core, Patientstatus, DFSmonth, OSmonth, grade, contains("status")) %>% 
  mutate(vital_status = grepl("death", Patientstatus)) 
```

```{r}
spatial_level <- basel_output$spatial_score > median(basel_output$spatial_score)
```


```{r}
df_surv <- inner_join(
  df_surv,
  enframe(basel_output$spatial_score, "core", "spatial_score")
)
```

```{r}
select(df_surv, spatial_score, contains("Status", ignore.case=FALSE)) %>% 
  gather(receptor, status, -spatial_score) %>% 
  ggplot(aes(x = status, y = spatial_score)) +
  geom_boxplot() +
  facet_wrap(~ receptor) +
  ggsignif::geom_signif(comparisons = list(c("negative", "positive")))
```


```{r}
df_surv2 <- group_by(df_surv, PID, Patientstatus, DFSmonth, OSmonth, vital_status, grade) %>% 
  summarize(spatial_score = mean(spatial_score)) %>% 
  ungroup() 
```



```{r}
q <- quantile(df_surv2$spatial_score, c(0.25, 0.75))
df_surv2 <- mutate(df_surv2,
                  level = case_when(
                    spatial_score > q[2] ~ "high",
                    spatial_score < q[1] ~ "low"
                  ))
```

```{r}
save.image(paste0(params$kaplan_meier, "-img.rds"))
# load("../../output/squirrel/figures/spatial/km.pdf-img.rds")
```

```{r}
grades <- sort(unique(df_surv2$grade))
```


````{r}
df_tmp <- filter(df_surv2)

fit <- survfit(Surv(DFSmonth, vital_status) ~ level + grade, data = drop_na(df_tmp))

```

```{r}
plt <- ggsurvplot(fit, 
           pval = surv_pvalue(fit)[1,4],
           palette = "Set1",
           legend.title = NA,
           conf.int=TRUE)
```

```{r}
km <- plt$plot
km
```

```{r}
# km$data$strata <- gsub("grade", "", km$data$strata)
# km$data$strata <- gsub("level", "", km$data$strata)
```

```{r}
originals <- levels(as.factor(km$data$strata))
new <- gsub("grade", "\nTumor grade", originals)
new <- gsub("level", "\nSpatial score", new, fixed=TRUE)
```


```{r, eval=FALSE}

cols <- c(
  "#a1d99b",
  "#31a354",
  "#9ecae1",
  "#3182bd",
  "#fc9272",
  "#de2d26")
names(cols) <- originals

km + scale_colour_manual(values=cols,
                         labels = new) +
  scale_linetype(labels=new) +
  theme(legend.text = element_text(size = 10),
        legend.title = element_blank(),
        legend.position = "right",
        legend.spacing.y = unit(1.0, 'cm'))  +
  labs(x = "Time (months)", y = "Disease free\nsurvival probability")
```

```{r}
pdf(params$kaplan_meier, width = 6, height = 3.5)
print(last_plot())
dev.off()
```

# Consistency with pathologist annotated cell types

```{r}
cells_counted_basel <- read_tsv(params$cells_counted_basel)
```

```{r}
df_ast <- select(cells_counted_basel, -n) %>% 
  spread(cell_type, frac_cells, fill = 0)
```

```{r}
df_ast$astir_epithelial <- df_ast$`Epithelial (basal)` + df_ast$`Epithelial (luminal)` + df_ast$`Epithelial (other)`
df_ast$astir_inflammatory <- df_ast$`B cells` + df_ast$`T cells` + df_ast$Macrophage
df_ast$astir_stromal <- df_ast$Stromal 
```



```{r}
pathologist <- select(mdata, core, contains("%")) %>% 
  dplyr::rename(pct_inflammatory = `%inflammatorycells`,
         pct_stromal = `%stroma`,
         pct_tumour = `%tumorcells`,
         pct_normal = `%normalepithelialcells`)
```

```{r}
df_ast_path <- inner_join(df_ast, pathologist, by = "core")
```

```{r}
t1 <- tidy(cor.test(df_ast_path$pct_stromal, df_ast_path$astir_stromal))

ggplot(df_ast_path, aes(x = pct_stromal, y = 100 * astir_stromal)) +
  geom_point(alpha = 0.5, size =2) +
  cowplot::theme_cowplot() +
  geom_smooth(method="lm", colour = "darkred", linetype=2) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 3)) +
  labs(
    x = "% Stromal cells\n(pathologist estimate)",
    y = "% Stromal cells\n(astir estimate)",
    subtitle = paste("Correlation =", roundn(t1$estimate, 2), "\np = ", format(t1$p.value,digits=3))
  ) 

stromal_plot <- last_plot()
```

```{r}
t2 <- tidy(cor.test(df_ast_path$pct_inflammatory, df_ast_path$astir_inflammatory))

ggplot(df_ast_path, aes(x = pct_inflammatory, y = 100 * astir_inflammatory)) +
  geom_point(alpha = 0.5, size =2) +
  cowplot::theme_cowplot() +
  geom_smooth(method="lm", colour = "darkred", linetype=2) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 3)) +
  labs(
    x = "% Inflammatory\n(pathologist estimate)",
    y = "% T, B, and macrophage cells\n(astir estimate)",
    subtitle = paste("Correlation =", roundn(t2$estimate, 2), "\np = ", format(t2$p.value, digits=3))
  )

inf_plot <- last_plot()
```

```{r}
t3 <- tidy(cor.test(df_ast_path$pct_tumour + df_ast_path$pct_normal, df_ast_path$astir_epithelial))

ggplot(df_ast_path, aes(x = pct_tumour + pct_normal, y = 100 * astir_epithelial)) +
  geom_point(alpha = 0.5, size =2) +
  cowplot::theme_cowplot() +
  geom_smooth(method="lm", colour = "darkred", linetype=2) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 3)) +
  labs(
    x = "% Tumour and normal cells\n(pathologist estimate)",
    y = "% Epithelial cells\n(astir estimate)",
    subtitle = paste("Correlation =", roundn(t2$estimate, 2), "\np = ", format(t3$p.value, digits=3))
  ) 

epi_plot <- last_plot()
```

```{r}
cowplot::plot_grid(epi_plot, inf_plot, stromal_plot, nrow=1)
```

```{r}
pdf(params$pathologist_plot, width = 9.5, height = 3.2)
print(last_plot())
dev.off()
```

# Hmm

```{r}
spat_score <- basel_output$spatial_score
```

```{r}
df <- enframe(spat_score, "core", "spatial_score") %>% 
  inner_join(cells_counted_basel, by = "core")

df
```

```{r}
ggplot(df, aes(x = spatial_score, y = frac_cells)) +
  geom_point() +
  facet_wrap(~ cell_type, scales = "free_y")
```
```{r}
df_t <- filter(df, cell_type == "T cells") %>% 
  mutate(
    core_type = case_when(
      spatial_score > median(spatial_score) & frac_cells > median(frac_cells) ~ "Hot-mixed",
      spatial_score < median(spatial_score) & frac_cells > median(frac_cells) ~ "Hot-compart",
      TRUE ~ "cold"
    )
  )

ggplot(df_t, aes(x = spatial_score, y = frac_cells, colour = core_type)) +
  geom_point()
```




```{r}
df_surv <- filter(mdata, diseasestatus == "tumor") %>% 
  select(PID, core, Patientstatus, DFSmonth, OSmonth, grade, contains("status")) %>% 
  mutate(vital_status = grepl("death", Patientstatus)) 
```

```{r}
df_surv <- inner_join(df_surv, df_t, by = "core")
```



````{r}
fit1 <- survfit(Surv(DFSmonth, vital_status) ~ core_type, data = filter(df_surv, grade == "1"))
fit2 <- survfit(Surv(DFSmonth, vital_status) ~ core_type, data = filter(df_surv, grade == "2"))
fit3 <- survfit(Surv(DFSmonth, vital_status) ~ core_type, data = filter(df_surv, grade == "3"))
```

```{r}
plt1 <- ggsurvplot(fit1, 
           pval = surv_pvalue(fit1)[1,4],
           palette = "Set1",
           legend.title = NA,
           conf.int=TRUE)

plt2 <- ggsurvplot(fit2, 
           pval = surv_pvalue(fit2)[1,4],
           palette = "Set1",
           legend.title = NA,
           conf.int=TRUE)

plt3 <- ggsurvplot(fit3, 
           pval = surv_pvalue(fit3)[1,4],
           palette = "Set1",
           legend.title = NA,
           conf.int=TRUE)
```

```{r}
cowplot::plot_grid(plt1$plot, plt2$plot, plt3$plot, nrow = 1)
```










