---
title: "ClusterX different cell type proportions"
author: "Michael Geuenich"
date: "November 24, 2020"
output: html_document
params:
  markers: "all_markers"
  cells: "output/chipmunk/sces/wagner_sce.rds"
  cellSubset: "output/chipmunk/results/epithelial_overclustering/luminal_20.csv" 
  markers_list: ""
  output_results: ""
  percent_luminal: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../../')
library(tidyverse)
library(devtools)
library(SingleCellExperiment)
library(cytofkit)
library(GSVA)
library(taproom)
source("scripts/functions.R")
```


```{r}
cell_subset <- read_csv(params$cellSubset)

sce <- readRDS(params$cells)[,cell_subset$cell_id]

percent_luminal <- params$percent_luminal
```


Clustering
```{r}
markers <- read_markers(params$markers_list)

if(params$markers == "all_markers"){
  imc.data <- t(logcounts(sce))
}else if(params$markers == "specified_markers"){  
  imc.data <- t(logcounts(sce[unique(unlist(markers$cell_types)),]))
}

imc.tsne <- cytof_dimReduction(data=imc.data, method = "tsne")
imc.clusterX.cluster <- cytof_cluster(ydata = imc.tsne, method = "ClusterX")

sce$clusterX <- imc.clusterX.cluster

ClusterX <- sce %>% 
  colData() %>% 
  as.data.frame() %>% 
  select(id, "clusterX")
```

Gene set enrichment analysis
```{r}
gsva_markers <- list(cell_types = markers[["cell_types"]][c("Stromal", "T cells", "Epithelial (luminal)", "Macrophage")], cell_states = "")

gsva <- gsva(logcounts(sce),
          gsva_markers$cell_types,
          method="gsva")

df_gsva <- t(gsva) %>% 
  as.data.frame() %>% 
  rownames_to_column("id") %>% 
  gather(pathway, score, -id) %>% 
  as_tibble()
```

```{r message=F}
cluster_cell_type_scores <- inner_join(df_gsva, ClusterX) %>% 
  group_by(pathway, clusterX) %>%
  dplyr::summarize(mean_score = mean(score)) %>% 
  ungroup() %>% 
  group_by(pathway) %>% 
  mutate(mean_score = (mean_score - mean(mean_score)) / sd(mean_score)) %>% 
  ungroup() %>% 
  group_by(clusterX) %>% 
  mutate(thresh_score = mean_score == max(mean_score)) %>% 
  filter(thresh_score == TRUE)


ClusterX <- inner_join(ClusterX, cluster_cell_type_scores) %>% 
  select(-c(mean_score, thresh_score)) %>% 
  dplyr::rename("cell type" = "pathway")
```

```{r}
ClusterX$method <- "ClusterX"
ClusterX$params <- paste(params$markers, "Default", sep = "_")
ClusterX$percent_epithelial <- percent_luminal
write.csv(ClusterX, file = paste0(params$output_results, 
                                  "Epithelial_overclustering_ClusterX_clusters-",
                                  params$markers, "-default-", percent_luminal, ".csv"),
          col.names = T, row.names = F, sep = ",", quote = FALSE)

```