---
title: "Robustness figures"
output: html_document
params:
  output_fig_removed: "removed.pdf"
  output_fig_added: "added.pdf"
  markers: markers.yml
  input_dir: '../../output/v5/robustness/'
  thresh: 0.95
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages({
  library(tidyverse)
  library(devtools)
  library(glue)
  library(ggalluvial)
  library(cowplot)
  library(matrixStats) 
  library(pheatmap)
  library(glue)
  library(taproom)
  library(yaml)
})

```

```{r}
markers <- read_yaml(params$markers)
```


# Define palette

```{r}
celltype_colours <- taproom::jackson_basel_colours()
celltype_colours <- c(celltype_colours, "Endothelial"="red")
```


# Removing cell types

```{r}
removed_csvs <- dir(params$input_dir, pattern = 'removed*.*csv', 
                    full.names = TRUE)
```


Have a look at the full assigned celltypes
```{r}
mat <- read_csv(removed_csvs[1])
mat <- arrange(mat, X1)
mat$X1 <- NULL
```

```{r}
# mat_all <- read_csv("../../output/v4/basel_subset/basel_subset_assignments.csv")
# mat_all <- arrange(mat_all, X1)
# mat_all$X1 <- NULL
```

```{r}
# table(
#   get_celltypes(mat, thresh = 0.95),
#   get_celltypes(mat_all, thresh = 0.95)
# )
```


# Subsets

```{r}
read_to_mat <- function(f) {
  df <- read_csv(f)
  mat <- as.matrix(select(df, -X1))
  celltypes <- get_celltypes(mat, thresh = params$thresh)

  condition <- strsplit(f, "-")[[1]]
  condition <- condition[length(condition)]
  condition <- gsub(".csv", "", condition, fixed=TRUE)
 
  tibble(
    cell = df$X1,
    cell_type = celltypes,
    condition = condition
  ) 
}
```

```{r}
df <- map_dfr(removed_csvs, read_to_mat)

df$condition <- gsub("_", " ", df$condition)

df$condition <- factor(df$condition,
                       levels = c(
                         "None",
                         "Stromal only",
                         "Stromal Macrophage",
                         "Stromal Macrophage Endothelial"
                       ))
```

```{r}
cells_stromal_none <- filter(df, 
                             condition == "None", 
                             cell_type %in% c("Stromal", "Macrophage", "Endothelial")) %>% 
  .$cell
```


```{r}
filter(df, cell %in% cells_stromal_none) %>% 
  ggplot(aes(x = condition, stratum = cell_type, alluvium = cell,
               fill = cell_type)) +
  geom_stratum(alpha = .5) +
  #geom_label(stat = "stratum", size = 3) +
  cowplot::theme_cowplot(font_size = 12) +
  stat_flow() +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = celltype_colours, name = "Cell type assigned") +
  theme(axis.text.x = element_text(angle = -45, hjust = 0, vjust = 0.5)) +
  labs(x = "Cell type removed")
```

```{r}
pdf(params$output_fig_removed, width = 5, height=3.5)
print(last_plot())
dev.off()
```


```{r}
# ggplot(df, aes(x = condition, stratum = cell_type, alluvium = cell,
#                fill = cell_type, label = cell_type)) +
#   geom_stratum(alpha = .5) +
#   geom_label(stat = "stratum", size = 3) +
#   cowplot::theme_cowplot(font_size = 12) +
#   stat_flow() +
#   scale_x_discrete(expand = c(0,0)) +
#   scale_y_discrete(expand = c(0,0)) +
#   scale_fill_manual(values = celltype_colours, name = "Cell type\nassigned") +
#   theme(axis.text.x = element_text(angle = -45, hjust = 0, vjust = 0.5)) +
#   labs(x = "Celltype removed")
```

Generate some statistics:

```{r}
stromal_first_cells <- filter(df, condition == "None", cell_type == "Stromal") %>% 
  .$cell

ct <- filter(df, cell %in% stromal_first_cells, condition == "Stromal only") %>% 
  .$cell_type

print(table(ct))
```

```{r}
print(mean(ct == "Unknown"))
```


```{r}
macrophage_second_cells <- filter(df, condition == "Stromal only", cell_type == "Macrophage") %>% 
  .$cell

ct <- filter(df, cell %in% macrophage_second_cells, condition == "Stromal Macrophage") %>% 
  .$cell_type
print(table(ct))
```

```{r}
print(mean(ct == "Unknown"))
```


```{r}
endo_third_cells <- filter(df, condition == "Stromal Macrophage", cell_type == "Endothelial") %>% 
  .$cell

ct <- filter(df, cell %in% endo_third_cells, condition == "Stromal Macrophage Endothelial") %>% 
  .$cell_type

print(table(ct))
```

```{r}
print(mean(ct == "Unknown"))
```


# Adding celltypes


```{r}
added_csvs <- dir(params$input_dir, pattern = 'added*.*csv', 
                    full.names = TRUE)
```

```{r}
read_to_mat <- function(f) {
  df <- read_csv(f)
  mat <- as.matrix(select(df, -X1))
  celltypes <- get_celltypes(mat, thresh = params$thresh)

  condition <- strsplit(f, "-")[[1]]
  condition <- condition[length(condition)]
  condition <- gsub(".csv", "", condition, fixed=TRUE)
 
  tibble(
    cell = df$X1,
    cell_type = celltypes,
    condition = condition
  ) 
}
```

```{r}
df <- map_dfr(added_csvs, read_to_mat)

df$condition <- gsub("_", " ", df$condition)

df$condition <- factor(df$condition,
                       levels = c(
                         "One additional",
                         "Two additional",
                         "Three additional"
                       ))
```

```{r}
declared_celltypes <- c(
  names(markers$cell_types),
  "Unknown",
  "Other"
)
```


```{r}
dplyr::count(df, condition, cell_type) 
```

```{r}
df %>% 
  group_by(condition) %>% 
  summarize(
    wrong_mean = mean(!(cell_type %in% declared_celltypes))
  )
```


```{r}
ggplot(df, aes(x = condition, stratum = cell_type, alluvium = cell,
               fill = cell_type)) +
  geom_stratum(alpha = .5) +
  cowplot::theme_cowplot(font_size = 12) +
  stat_flow() +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_manual(values = celltype_colours, name = "Cell type assigned") +
  theme(axis.text.x = element_text(angle = -45, hjust = 0, vjust = 0.5)) +
  labs(x = "Cell type added")
```

```{r}
pdf(params$output_fig_added, width = 5, height=3.5)
print(last_plot())
dev.off()
```

